# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ce758c0823498a40f2dba9679bba1b993246dc883a73cfbd3dafe95d7fbf78a5da27fbf5a1da95c532d5274a08525fecde4275e155139ea34e0d4a4d7cce23e

test:
  secret_key_base: d248fa6e57d358cf813727fe9f54efc1bef0cb0238602520244fc81e955e480e5a213689c31525fc22983636f4d6229cf55e5366474531b6904f13dbc844d07c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
